### ISSUE TITLE
Needed java JDK download for uploader to work

### ISSUE THREAD

**Issue by shlake** [IQSS/dataverse-uploader#1]
Per installation Step 1 on the wiki:
https://github.com/IQSS/dataverse-uploader/wiki/DVUploader,-a-Command-line-Bulk-Uploader-for-Dataverse

I followed the link to download JAVA, downloaded and installed.
But when I ran the DVUploader, got an error message (on a Mac):
" No Java Runtime present,requesting to install "  

I had to also install the JDK from this page:
https://www.oracle.com/technetwork/java/javase/downloads/jdk12-downloads-5295953.html

So maybe include this tip (need an extra download for Macs?) in the installation instructions?

After installing the JDK, worked just fine!!!! Thanks @qqmyers

**Comment by qqmyers** [comment]
@shlake  - thanks for the report. 

I'm not a Mac expert but it appears that Macs don't like to run command-line java tools with just a JRE (https://anas.pk/2015/09/02/solution-no-java-runtime-present-mac-yosemite/ was one note about it). Downloading the full JDK looks like it works (and you wouldn't have to do the first download of the JRE at all), but it seems like overkill (because your downloading things only used in development). The website above mentions that one can alter the path (a sym link) to java to use the JRE instead, but I have no way to try that.

If anyone has more Mac experience and can suggest the best instructions to give, let me know. I guess for now I'll mention that Mac users should download the JDK instead - that's probably easier than talking about the sym link to java, etc..

**Comment by shlake** [comment]
@qqmyers, yes, special mention for Mac users is easiest.

**Comment by pdurbin** [comment]
I guess the only thing I'd mention is that while it's completely fine to get Java from Oracle (who owns the trademark to Java and leads development), users can also download Java for a wide variety of platforms from https://adoptopenjdk.net (which I what I do for Mac).

**Comment by qqmyers** [comment]
OK - updated online. Also - note that I made a v1.0.5 release that has a security fix for problems in the jackson-databind library the uploader uses.
